### ISSUE TITLE
Unknown prop `nogutter` on <div> tag

### ISSUE THREAD

**Issue by sheez44** [JSxMachina/react-grid-system#52] opened 2018-03-02 13:12 UTC
When using 'nogutter' i get this error in development:
`warning.js?6327:33 Warning: Unknown prop `nogutter` on <div> tag. Remove this prop from the element.` 

The functionality works but it clutters the console quite a lot.

**Comment by gerbenmeyer** [comment] 2018-04-23 19:52
I can't reproduce this. Are you sure you're only adding `nogutter` to the `Row` component?

**Comment by gerbenmeyer** [comment] 2018-05-24 20:42
Let me know if you still have this issue. Till then, I'll close this.

**Closed by gerbenmeyer** 2018-05-24 20:42 UTC

**Comment by sheez44** [comment] 2018-05-28 08:21
It seems to fixed somehow
